# Generated by Django 5.0.1 on 2024-01-17 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="ID",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="department",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="Department",
            new_name="department",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="ID",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="Manager_ID",
            new_name="manager_id",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="Name",
            new_name="name",
        ),
    ]
