# Generated by Django 5.0.1 on 2024-01-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0002_rename_id_department_id_rename_name_department_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=32),
        ),
    ]
